#!/bin/bash

branch=$(git branch --show-current)
master_branch="master"
branch_regexp="^[A-Z]+\-[0-9]+\-.+$"
# Check a branch name
if [[ $branch -ne master_branch && ! $branch =~ $branch_regexp ]]; then
  echo "[INVALID BRANCH NAME]"
  echo "e.g.) JIRA-123-feature-description"
  exit 1
fi
